# Generated by Django 3.0.7 on 2020-06-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20200606_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='entry_type',
            field=models.CharField(choices=[('in', 'income'), ('out', 'expense')], max_length=10),
        ),
    ]
